MyPythonTrainer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls', namespace='userapp')),
    path('course/', include('courseapp.urls', namespace='courseapp')),
    path('trainer/', include('trainers.urls', namespace='trainers')),
    path('batch/', include('batchapp.urls', namespace='batchapp')),
    path('student/', include('studentapp.urls',namespace='studentapp')),
    path('admins/', include('adminapp.urls',namespace='adminapp')),
    path('topic/', include('topicapp.urls', namespace='topicapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainers/urls.py
from django.urls import path
from . import views

app_name = "trainers"
urlpatterns = [
    path('', views.TrainerFormView.as_view(), name='trainer_create'),
    path('trainers/', views.TrainersListView.as_view(), name='trainer_view'),
    path('Degree/', views.DegreeView.as_view(), name='Degree'),
    path('DegreeAdd/', views.DegreeAdd.as_view(), name='DegreeAdd'),
    path('DegreeSuccess/', views.DegreeSuccess.as_view(), name='DegreeSuccess'),
    path('DegreeList/', views.DegreeList.as_view(), name='DegreeList'),
    path('College/', views.CollegeView.as_view(), name='College'),
    path('CollegeAdd/', views.CollegeAdd.as_view(), name='CollegeAdd'),
    path('CollegeSuccess/', views.CollegeSuccess.as_view(), name='CollegeSuccess'),
    path('CollegeList/', views.CollegeList.as_view(), name='CollegeList'),
    path('Qualification/', views.QualificationsView.as_view(), name='Qualification'),
    path('QualificationAdd/', views.QualificationAdd.as_view(), name='QualificationAdd'),
    path('QualificationSuccess/', views.QualificationSuccess.as_view(), name='QualificationSuccess'),
    path('QualificationList/', views.QualificationList.as_view(), name='QualificationList'),
    path('Organization/', views.OrganizationView.as_view(), name='Organization'),
    path('OrganizationAdd/', views.OrganizationAdd.as_view(), name='OrganizationAdd'),
    path('OrganizationSuccess/', views.OrganizationSuccess.as_view(), name='OrganizationSuccess'),
    path('OrganizationList/', views.OrganizationList.as_view(), name='OrganizationList'),
    path('Award/', views.AwardsView.as_view(), name='Award'),
    path('AwardAdd/', views.AwardAdd.as_view(), name='AwardAdd'),
    path('AwardSuccess/', views.AwardSuccess.as_view(), name='AwardSuccess'),
    path('AwardList/', views.AwardList.as_view(), name='AwardList'),
    path('<int:trainer_id>', views.TrainerDetailView.as_view(), name='trainer_one'),
    path('toggle-status/<int:pk>/', views.TrainerToggleStatus.as_view(), name='trainer_toggle_status'),
    path('stories/',views.CourseFeedbackListView.as_view(),name='stories'),
    path('feedback/approve/<int:feedback_id>/', views.approve_feedback, name='approve_feedback'),
    path('feedback/reject/<int:feedback_id>/', views.reject_feedback, name='reject_feedback'),

]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('adminregistration/', views.RegisterAdminView.as_view(), name='register-admin'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.NewIndexPageView.as_view(), name='home'),  # Home URL for students
    # path('home/', views.IndexPageView.as_view(), name='index_page'),  # Home URL for students
    # path('about/', views.AboutPageView.as_view(), name='about_page'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
    path('my-enrolled-courses/', views.AppliedCoursesView.as_view(), name='applied_courses'),
    path('user/profile/view', views.UserProfileView.as_view(), name='user_profile_view'),
    path('user/profile/edit', views.UserProfileEdit.as_view(), name='user_profile_edit'),

    path('view/', views.CourseListView.as_view(), name='course_view'),
    path('<int:course_id>', views.CourseDetailView.as_view(), name='each_course'),
    # path('registration/<str:course_title>/', views.CourseRegistration.as_view(), name='course_regs'),

    # JC - New UI
    path('home/', views.NewIndexPageView.as_view(), name='new_index_page'),
    path('trainers/', views.NewAboutPageView.as_view(), name='new_about_page'),
    path('courses/', views.NewCoursesPageView.as_view(), name='new_courses_page'),
    path('course-calendar/', views.NewCourseCalendarPageView.as_view(), name='new_courses_calendar_page'),
    path('stories/', views.NewStoriesPageView.as_view(), name='new_stories_page'),
    path('contact/', views.NewContactPageView.as_view(), name='new_contact_page'),
    path('privacy-policy/', views.PrivacyPolicyPageView.as_view(), name='privacy_policy'),
    path('terms-conditions/', views.TermsConditionsPageView.as_view(), name='terms_conditions'),
    path('refund-policy/', views.RefundPolicyPageView.as_view(), name='refund_policy'),
    path('register/', views.NewRegistrationPageView.as_view(), name='new_registration_page'),
    path('login/', views.NewLoginPageView.as_view(), name='login'),
    path('payment/proceed/<int:course_id>/<str:payment_type>/', views.MakePaymentView.as_view(), name='make_payment'),
    path('course/enroll/<str:course_title>/<str:batch_name>', views.EnrollCourse.as_view(), name='new_course_enrollment'),
    path('confirm_enrollment/<str:course_title>/<str:batch_name>/', views.ConfirmEnrollCourse.as_view(), name='confirm_enrollment'),
    path('payment/verify/', views.PaymentVerificationView.as_view(), name='payment_verification'),
    path('payment/failed/', views.PaymentFailedView.as_view(), name='payment_failed'),
    path('payment/success/', views.PaymentSuccessView.as_view(), name='payment_success'),
    path('batch/details/<str:batch_number>', views.BatchDetailView.as_view(), name='batch_details'),
    path('feedback/',views.CourseFeedbackCreateView.as_view(),name='feedback'),
    path('feedbackSuccess/',views.FeedbackSuccessView.as_view(),name='feedback-success'),
    path('feedbackList/',views.CourseFeedbackListView.as_view(),name='feedback-List'),
]

trainers/views.py
from django.shortcuts import get_object_or_404, redirect
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django import forms
from .models import Trainer, Degree, College, Qualification, Organization, Award
from django.urls import reverse_lazy, reverse
from django.views.generic import View, UpdateView, DeleteView, FormView, ListView, DetailView, TemplateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# create a model form
class TrainerForm(forms.ModelForm):
    class Meta:
        model = Trainer
        fields = '__all__'
        exclude = ['status']

    def __init__(self, *args, **kwargs):
        super(TrainerForm, self).__init__(*args, **kwargs)
        # Make the country_code field uneditable
        self.fields['country_code'].disabled = True

    def clean_email(self):
        email = self.cleaned_data.get('email')

        # If editing an existing trainer (not creating a new one)
        if self.instance and self.instance.pk:
            # Check if the email has been changed
            if email and Trainer.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise ValidationError('A trainer with this email already exists.')
        else:
            # For new trainer creation, ensure the email is unique
            if Trainer.objects.filter(email=email).exists():
                raise ValidationError('A trainer with this email already exists.')

        return email


# Create your views here.
class TrainerFormView(LoginRequiredMixin, FormView):
    form_class = TrainerForm
    template_name = 'trainers/trainer.html'
    success_url = reverse_lazy('trainers:trainer_view')

    def form_valid(self, form):
        trainer = form.save()
        trainer_name = trainer.name
        messages.success(self.request, f'Trainer "{trainer_name}" created successfully')
        return super().form_valid(form)


# list trainers
class TrainersListView(LoginRequiredMixin, ListView):
    model = Trainer
    context_object_name = 'data'
    template_name = 'trainers/trainers.html'
    ordering = ['-name']

    def post(self, request, *args, **kwargs):
        # Handle the status change when a checkbox is toggled
        trainer_id = request.POST.get('trainer_id')
        trainer = get_object_or_404(Trainer, id=trainer_id)
        trainer.status = not trainer.status  # Toggle the status
        trainer.save()

        # Redirect to the same page after the status is toggled
        return redirect('trainers:trainer_view')

    def get_queryset(self):
        queryset = super().get_queryset().all().order_by('name')
        return queryset


# view each trainer details
class TrainerDetailView(LoginRequiredMixin, DetailView):
    model = Trainer
    template_name = 'trainers/each_trainer.html'
    context_object_name = 'new'

    def get_object(self):
        trainer_id = self.kwargs.get('pk')
        # print(trainer_id)
        return get_object_or_404(Trainer, pk=trainer_id)


# remove trainer


class TrainerToggleStatus(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        trainer = Trainer.objects.get(pk=self.kwargs['pk'])  # Fetch the trainer by primary key

        # Check if the trainer is assigned to any courses
        if trainer.course_set.exists():
            course_names = ", ".join([course.title for course in trainer.course_set.all()])
            messages.error(request,
                           f'Trainer "{trainer.name}" is assigned to "{course_names}". Please untag them from the course(s) to deactivate.')
            return redirect('trainers:trainer_view')  # Redirect back to the trainer view page

        # Toggle the status
        trainer.status = not trainer.status
        trainer.save()

        # Send a success message
        if trainer.status:
            messages.success(request, f'Trainer "{trainer.name}" has been activated.')
        else:
            messages.success(request, f'Trainer "{trainer.name}" has been deactivated.')

        # Redirect back to the trainer view
        return redirect('trainers:trainer_view')


# edit a trainer


# class TrainerToggleStatus(LoginRequiredMixin, View):
#     def post(self, request, *args, **hytrewq
#         trainer = Trainer.objects.get(pk=kwargs['pk'])

#         # Toggle the trainer's status
#         if trainer.status:  # If active, trying to deactivate
#             if trainer.course_set.exists():  # Check if trainer is assigned to any course
#                 course_names = ", ".join([course.title for course in trainer.course_set.all()])
#                 messages.error(self.request, f'Trainer "{trainer.name}" is already assigned to "{course_names}". Please untag them from the course(s) to deactivate.')
#                 return redirect(reverse('trainers:trainer_view'))  # Redirect back to trainer list

#             # Deactivate the trainer
#             trainer.status = False
#             messages.success(self.request, f'Trainer "{trainer.name}" has been deactivated.')
#         else:
#             # Activate the trainer
#             trainer.status = True
#             messages.success(self.request, f'Trainer "{trainer.name}" has been activated.')

#         trainer.save()
#         return redirect(reverse('trainers:trainer_view'))  # Redirect back to the trainer list after action

class DegreeView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/Degree.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class DegreeForm(forms.ModelForm):
    class Meta:
        model = Degree
        fields = "__all__"


class DegreeAdd(FormView):
    form_class = DegreeForm
    template_name = "trainers/DegreeAdd.html"
    success_url = reverse_lazy('trainers:DegreeSuccess')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class DegreeSuccess(TemplateView):
    template_name = 'trainers/DegreeSuccess.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "A NEW DEGREE IS ADDED SUCCESSFULLY"
        return context


class DegreeList(ListView):
    template_name = "trainers/DegreeList.html"
    model = Degree
    context_object_name = "deg"


"______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"


class CollegeView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/College.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class CollegeForm(forms.ModelForm):
    class Meta:
        model = College
        fields = "__all__"


class CollegeAdd(FormView):
    form_class = CollegeForm
    template_name = "trainers/CollegeAdd.html"
    success_url = reverse_lazy("trainers:CollegeSuccess")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CollegeSuccess(TemplateView):
    template_name = "trainers/CollegeSuccess.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "A NEW COLLEGE IS ADDED SUCCESSFULLY"
        return context


class CollegeList(ListView):
    template_name = "trainers/CollegeList.html"
    model = College
    context_object_name = "clg"


"________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"


class QualificationsView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/Qualification.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class QualificationForm(forms.ModelForm):
    class Meta:
        model = Qualification
        fields = "__all__"


class QualificationAdd(FormView):
    form_class = QualificationForm
    template_name = "trainers/QualificationAdd.html"
    success_url = reverse_lazy("trainers:QualificationSuccess")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class QualificationSuccess(TemplateView):
    template_name = "trainers/QualificationSuccess.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "A QUALIFICATION IS ADDED SUCCESSFULLY"
        return context


class QualificationList(ListView):
    template_name = "trainers/QualificationList.html"
    model = Qualification
    context_object_name = "qua"


"_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"


class OrganizationView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/Organization.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class OrganizationForm(forms.ModelForm):
    class Meta:

userapp/templates/userapp/applied_courses.html
{% extends 'userapp/new-base.html' %}
{% load static %}
{% load humanize %}
{% load custom_filters %}
{% block title %}My Enrolled Courses{% endblock %}
{% block content %}

<section id="complete_python" class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h4>My Enrolled Courses</h4>
                {% if applied_courses %}
                <style>
                    #enroll-instructions ul li {
                        font-size: 14px;
                    }
                </style>
                <p>Here you can find details of all the batches that you've applied for. Please note that,</p>
                <div id="enroll-instructions">
                    <ul>
                        <li>In case of <b>Payment Pending</b>, You've to <b>Book a Seat</b> on or before mentioned due date. Otherwise, your enrollment will be <b>Auto Cancelled.</b></li>
                        <li>In case of <b>Seat Reserved</b>, After the demo class, You've to <b>Confirm your Seat</b> if you want to continue with complete course.</li>
                        <li>In case of <b>Seat Confirmed</b>, You are <b>All set</b>! Just, focus on the learning and All the Best!</li>
                    </ul>
                </div>
                {% endif %}

                <div class="col-12">
                    <div class="mobile-respon mt-4">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Course</th>
                                    <th>Class Details</th>
                                    <th>Links</th>
                                    <th>Enrollment Details</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if applied_courses %}
                                    {% for enrollment in applied_courses %}
                                    <tr>
                                        <td>
                                            <b>{{ enrollment.batch.course.title }} ({{ enrollment.batch.batch_number }})</b><br />
                                            <span class="text-muted" style="font-size: 0.8em;">
                                                Demo: {{ enrollment.batch.start_date }} at {{ enrollment.batch.start_time|date:"h:i a" }}<br />
                                                Course Duration: {{ enrollment.batch.duration|course_duration_round }} months<br />
                                                Any queries, Contact ({{ enrollment.batch.poc_name }})<br/>
                                                on WhatsApp: +91 {{ enrollment.batch.poc_mobile_no }}
                                            </span>
                                        </td>

                                        <td>
                                            {{ enrollment.batch.start_time|date:"h:i a" }} - {{ enrollment.batch.end_time|date:"h:i a" }} IST<br />
                                            <span class="text-muted" style="font-size: 0.8em;">
                                                (Daily {{ enrollment.batch.time_difference }} hr, Weekly {{ enrollment.batch.class_per_week }} days, <b>{{ enrollment.batch.language }}</b>)
                                            </span>
                                        </td>

                                        <td>
                                            {% if enrollment.enrollment_status == 'pending' or enrollment.enrollment_status == 'deactivated' %}
                                                <u class="d-block mt-2">Demo Class Link</u>
                                                <u class="d-block mt-2">Regular Class Link</u>
                                                <u class="d-block mt-2">Course Material Link</u>
                                                <u class="d-block mt-2">Weekly Test Link</u>
                                            {% elif enrollment.enrollment_status == 'reserved' %}
                                                <a href="{{ enrollment.batch.class_room_link }}" target="_blank" rel="noreferrer nofollow" class="d-block mt-2">Demo Class Link</a>
                                                <u class="d-block mt-2">Regular Class Link</u>
                                                <u class="d-block mt-2">Course Material Link</u>
                                                <u class="d-block mt-2">Weekly Test Link</u>
                                            {% elif enrollment.enrollment_status == 'confirmed' %}
                                                <a href="{{ enrollment.batch.class_room_link }}" target="_blank" rel="noreferrer nofollow" class="d-block mt-2">Demo Class Link</a>
                                                <a href="{{ enrollment.batch.class_room_link }}" target="_blank" rel="noreferrer nofollow" class="d-block mt-2">Regular Class Link</a>
                                                <a href="{{ enrollment.batch.course_material_link }}" target="_blank" rel="noreferrer nofollow" class="d-block mt-2">Course Material Link</a>
                                                <a href="{{ enrollment.batch.quiz_link }}" target="_blank" rel="noreferrer nofollow" class="d-block mt-2">Weekly Test Link</a>
                                            {% endif %}
                                        </td>

                                        <td>
                                            {% if enrollment.enrollment_status in 'pending deactivated reserved confirmed' %}
                                                <span class="badge bg-warning">{{ enrollment.enrollment_status_display|capfirst }}</span><br/>
                                            {% endif %}

                                            <span class="text-muted" style="font-size: 0.8em;">
                                                Enrolled On: {{ enrollment.enrollment_date|date:"M d, Y" }}<br/>
                                            </span>

                                            {% if enrollment.adv_status %}
                                                {% if enrollment.full_status %}
                                                    <span class="text-muted" style="font-size: 0.8em;">
                                                        Seat Booked On: {{ enrollment.adv_payment_date|date:"M d, Y" }}<br/>
                                                        Seat Confirmed On: {{ enrollment.full_payment_date|date:"M d, Y" }}<br/>
                                                    </span>
                                                {% else %}
                                                    <span class="text-muted" style="font-size: 0.8em;">
                                                        Seat Booked On: {{ enrollment.adv_payment_date|date:"M d, Y" }}<br/>
                                                        (Please confirm your seat ASAP by paying the remaining amount!)<br/>
                                                        (All <b>Links</b> will be <b>enabled</b> after confirmation.)<br/>
                                                        <a href="{% url 'userapp:make_payment' enrollment.id 'full' %}" class="btn btn-primary btn-sm mt-2">Confirm Seat</a>
                                                    </span>
                                                {% endif %}
                                            {% else %}
                                                {% if enrollment.full_status %}
                                                    <span class="text-muted" style="font-size: 0.8em;">
                                                        Seat Booked On: {{ enrollment.full_payment_date|date:"M d, Y" }}<br/>
                                                        Seat Confirmed On: {{ enrollment.full_payment_date|date:"M d, Y" }}<br/>
                                                    </span>
                                                {% else %}
                                                    <span class="text-muted" style="font-size: 0.8em;">
                                                        (Please book your seat before <b>{{ enrollment.reservation_last_date|date:"M d, Y" }}</b> to avoid auto-cancellation.)<br/>
                                                        (Demo Link will activate after booking/confirmation.)
                                                    </span>
                                                {% endif %}
                                            {% endif %}
                                        </td>

                                        <td class="text-center">
                                            <a href="{% url 'userapp:feedback' %}" class="btn" style="background-color: #d9f99d; padding: 10px; border-radius: 10px;">
                                                <img src="{% static 'userapp/images/create_icon.png' %}" alt="Edit" style="height: 30px; width: 30px;">
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="5" class="text-center">You have not enrolled for any courses yet!</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

{% endblock %}

userapp/templates/userapp/password_reset_done.html
{% extends "userapp/new-base.html" %}
{% load static %}
{% block title %}Password Reset{% endblock %}
{% block content %}
<section id="complete_python" class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-4 lg-4 mx-auto">
                <div class="card mt-4 shadow-lg">
                    <div class="card-body p-4 text-center">
                        <h4 class="border-bottom mb-4 text-center" style="color: #f08d27;">
                            Password Reset
                        </h4>
                        <div class="mb-4">
                            <img src="{% static 'frontend_assets/images/success.png' %}" alt="Logo" width="100">
                        </div>
                        <p>If an active account is found with the email address provided, a link to reset the password will
                            be sent to the email address.</p>
                        <div class="pt-3 text-center">
                            <small class="text-muted mr-5">
                                <a href="{% url 'userapp:login' %}" class="ml-2 custom-link">Back to Login</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>

<section id="divider">
    <div class="container">
        <div class="ant-divider css-lujapw text-center">
            <span class="ant-divider-inner-text">
                <span role="img" aria-label="holder" class="anticon anticon-holder">
                    <svg viewBox="64 64 896 896" focusable="false" data-icon="holder" width="1em" height="1em"
                        fill="currentColor" aria-hidden="true">
                        <path
                            d="M300 276.5a56 56 0 1056-97 56 56 0 00-56 97zm0 284a56 56 0 1056-97 56 56 0 00-56 97zM640 228a56 56 0 10112 0 56 56 0 00-112 0zm0 284a56 56 0 10112 0 56 56 0 00-112 0zM300 844.5a56 56 0 1056-97 56 56 0 00-56 97zM640 796a56 56 0 10112 0 56 56 0 00-112 0z">
                        </path>
                    </svg>
                </span>
            </span>
        </div>
    </div>
</section>
{% endblock %}

userapp/templates/userapp/payment_failed.html
{% extends "userapp/new-base.html" %}
{% load static %}
{% block title %}Payment Failed{% endblock %}
{% block content %}
<section id="payment-status" class="mt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card mt-4 shadow-lg">
                    <div class="card-body p-4 text-center">
                        <h4 class="border-bottom mb-4" style="color: #f08d27;">
                            Payment Failed
                        </h4>
                        <div class="mb-4">
                            <img src="{% static 'frontend_assets/images/payment-failed.jpg' %}" alt="Payment Failed" width="200">
                        </div>
                        <p>{{ error_message }}</p>
                        <div class="pt-3">
                            <a href="{% url 'userapp:applied_courses' %}" 
                            class="btn btn-secondary">Go Back to My Enrolled Courses</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

userapp/templates/userapp/register.html
<!-- NOT USED -->
{% extends 'userapp/base.html' %}
<!--load crispy form-->
{% load crispy_forms_tags %}

{% block content %}

<section id="register" class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <!-- create a legend -->
                                <h1 class="display-6 border-bottom">
                                    Register
                                </h1>
                                {{form|crispy}}
                                
                            </div>
                            <!-- create a button -->
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-info btn-block">Sign Up</button>
                            </div>
                        </form>
                        <!-- if already having account -->
                        <div class="pt-2">
                            <small class="text-muted">Already Have an Account?
                                <a href="{% url 'userapp:login' %}" class="ml-3">Sign In</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}