MyPythonTrainer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls', namespace='userapp')),
    path('course/', include('courseapp.urls', namespace='courseapp')),
    path('trainer/', include('trainers.urls', namespace='trainers')),
    path('batch/', include('batchapp.urls', namespace='batchapp')),
    path('student/', include('studentapp.urls',namespace='studentapp')),
    path('admins/', include('adminapp.urls',namespace='adminapp')),
    path('topic/', include('topicapp.urls', namespace='topicapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('home/', views.AdminHomeView.as_view(), name='admin_home'),
    path('admin/profile/edit/', views.AdminProfileEdit.as_view(), name='admin_profile'),
    path('admin/profile/view/', views.AdminProfileView.as_view(), name='admin_view'),
]

trainers/urls.py
from django.urls import path
from . import views

app_name = "trainers"
urlpatterns = [
    path('', views.TrainerFormView.as_view(), name='trainer_create'),
    path('trainers/', views.TrainersListView.as_view(), name='trainer_view'),
    path('Degree/', views.DegreeView.as_view(), name='Degree'),
    path('DegreeAdd/', views.DegreeAdd.as_view(), name='DegreeAdd'),
    path('DegreeSuccess/', views.DegreeSuccess.as_view(), name='DegreeSuccess'),
    path('DegreeList/', views.DegreeList.as_view(), name='DegreeList'),
    path('College/', views.CollegeView.as_view(), name='College'),
    path('CollegeAdd/', views.CollegeAdd.as_view(), name='CollegeAdd'),
    path('CollegeSuccess/', views.CollegeSuccess.as_view(), name='CollegeSuccess'),
    path('CollegeList/', views.CollegeList.as_view(), name='CollegeList'),
    path('Qualification/', views.QualificationsView.as_view(), name='Qualification'),
    path('QualificationAdd/', views.QualificationAdd.as_view(), name='QualificationAdd'),
    path('QualificationSuccess/', views.QualificationSuccess.as_view(), name='QualificationSuccess'),
    path('QualificationList/', views.QualificationList.as_view(), name='QualificationList'),
    path('Organization/', views.OrganizationView.as_view(), name='Organization'),
    path('OrganizationAdd/', views.OrganizationAdd.as_view(), name='OrganizationAdd'),
    path('OrganizationSuccess/', views.OrganizationSuccess.as_view(), name='OrganizationSuccess'),
    path('OrganizationList/', views.OrganizationList.as_view(), name='OrganizationList'),
    path('Award/', views.AwardsView.as_view(), name='Award'),
    path('AwardAdd/', views.AwardAdd.as_view(), name='AwardAdd'),
    path('AwardSuccess/', views.AwardSuccess.as_view(), name='AwardSuccess'),
    path('AwardList/', views.AwardList.as_view(), name='AwardList'),
    path('<int:trainer_id>', views.TrainerDetailView.as_view(), name='trainer_one'),
    path('toggle-status/<int:pk>/', views.TrainerToggleStatus.as_view(), name='trainer_toggle_status'),
    path('stories/',views.CourseFeedbackListView.as_view(),name='stories'),
    path('feedback/approve/<int:feedback_id>/', views.approve_feedback, name='approve_feedback'),
    path('feedback/reject/<int:feedback_id>/', views.reject_feedback, name='reject_feedback'),

]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('adminregistration/', views.RegisterAdminView.as_view(), name='register-admin'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.NewIndexPageView.as_view(), name='home'),  # Home URL for students
    # path('home/', views.IndexPageView.as_view(), name='index_page'),  # Home URL for students
    # path('about/', views.AboutPageView.as_view(), name='about_page'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
    path('my-enrolled-courses/', views.AppliedCoursesView.as_view(), name='applied_courses'),
    path('user/profile/view', views.UserProfileView.as_view(), name='user_profile_view'),
    path('user/profile/edit', views.UserProfileEdit.as_view(), name='user_profile_edit'),

    path('view/', views.CourseListView.as_view(), name='course_view'),
    path('<int:course_id>', views.CourseDetailView.as_view(), name='each_course'),
    # path('registration/<str:course_title>/', views.CourseRegistration.as_view(), name='course_regs'),

    # JC - New UI
    path('home/', views.NewIndexPageView.as_view(), name='new_index_page'),
    path('trainers/', views.NewAboutPageView.as_view(), name='new_about_page'),
    path('courses/', views.NewCoursesPageView.as_view(), name='new_courses_page'),
    path('course-calendar/', views.NewCourseCalendarPageView.as_view(), name='new_courses_calendar_page'),
    path('stories/', views.NewStoriesPageView.as_view(), name='new_stories_page'),
    path('contact/', views.NewContactPageView.as_view(), name='new_contact_page'),
    path('privacy-policy/', views.PrivacyPolicyPageView.as_view(), name='privacy_policy'),
    path('terms-conditions/', views.TermsConditionsPageView.as_view(), name='terms_conditions'),
    path('refund-policy/', views.RefundPolicyPageView.as_view(), name='refund_policy'),
    path('register/', views.NewRegistrationPageView.as_view(), name='new_registration_page'),
    path('login/', views.NewLoginPageView.as_view(), name='login'),
    path('payment/proceed/<int:course_id>/<str:payment_type>/', views.MakePaymentView.as_view(), name='make_payment'),
    path('course/enroll/<str:course_title>/<str:batch_name>', views.EnrollCourse.as_view(), name='new_course_enrollment'),
    path('confirm_enrollment/<str:course_title>/<str:batch_name>/', views.ConfirmEnrollCourse.as_view(), name='confirm_enrollment'),
    path('payment/verify/', views.PaymentVerificationView.as_view(), name='payment_verification'),
    path('payment/failed/', views.PaymentFailedView.as_view(), name='payment_failed'),
    path('payment/success/', views.PaymentSuccessView.as_view(), name='payment_success'),
    path('batch/details/<str:batch_number>', views.BatchDetailView.as_view(), name='batch_details'),
    path('feedback/',views.CourseFeedbackCreateView.as_view(),name='feedback'),
    path('feedbackSuccess/',views.FeedbackSuccessView.as_view(),name='feedback-success'),
    path('feedbackList/',views.CourseFeedbackListView.as_view(),name='feedback-List'),
]

trainers/views.py
from django.shortcuts import get_object_or_404, redirect
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django import forms
from .models import Trainer, Degree, College, Qualification, Organization, Award
from django.urls import reverse_lazy, reverse
from django.views.generic import View, UpdateView, DeleteView, FormView, ListView, DetailView, TemplateView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# create a model form
class TrainerForm(forms.ModelForm):
    class Meta:
        model = Trainer
        fields = '__all__'
        exclude = ['status']

    def __init__(self, *args, **kwargs):
        super(TrainerForm, self).__init__(*args, **kwargs)
        # Make the country_code field uneditable
        self.fields['country_code'].disabled = True

    def clean_email(self):
        email = self.cleaned_data.get('email')

        # If editing an existing trainer (not creating a new one)
        if self.instance and self.instance.pk:
            # Check if the email has been changed
            if email and Trainer.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
                raise ValidationError('A trainer with this email already exists.')
        else:
            # For new trainer creation, ensure the email is unique
            if Trainer.objects.filter(email=email).exists():
                raise ValidationError('A trainer with this email already exists.')

        return email


# Create your views here.
class TrainerFormView(LoginRequiredMixin, FormView):
    form_class = TrainerForm
    template_name = 'trainers/trainer.html'
    success_url = reverse_lazy('trainers:trainer_view')

    def form_valid(self, form):
        trainer = form.save()
        trainer_name = trainer.name
        messages.success(self.request, f'Trainer "{trainer_name}" created successfully')
        return super().form_valid(form)


# list trainers
class TrainersListView(LoginRequiredMixin, ListView):
    model = Trainer
    context_object_name = 'data'
    template_name = 'trainers/trainers.html'
    ordering = ['-name']

    def post(self, request, *args, **kwargs):
        # Handle the status change when a checkbox is toggled
        trainer_id = request.POST.get('trainer_id')
        trainer = get_object_or_404(Trainer, id=trainer_id)
        trainer.status = not trainer.status  # Toggle the status
        trainer.save()

        # Redirect to the same page after the status is toggled
        return redirect('trainers:trainer_view')

    def get_queryset(self):
        queryset = super().get_queryset().all().order_by('name')
        return queryset


# view each trainer details
class TrainerDetailView(LoginRequiredMixin, DetailView):
    model = Trainer
    template_name = 'trainers/each_trainer.html'
    context_object_name = 'new'

    def get_object(self):
        trainer_id = self.kwargs.get('pk')
        # print(trainer_id)
        return get_object_or_404(Trainer, pk=trainer_id)


# remove trainer


class TrainerToggleStatus(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        trainer = Trainer.objects.get(pk=self.kwargs['pk'])  # Fetch the trainer by primary key

        # Check if the trainer is assigned to any courses
        if trainer.course_set.exists():
            course_names = ", ".join([course.title for course in trainer.course_set.all()])
            messages.error(request,
                           f'Trainer "{trainer.name}" is assigned to "{course_names}". Please untag them from the course(s) to deactivate.')
            return redirect('trainers:trainer_view')  # Redirect back to the trainer view page

        # Toggle the status
        trainer.status = not trainer.status
        trainer.save()

        # Send a success message
        if trainer.status:
            messages.success(request, f'Trainer "{trainer.name}" has been activated.')
        else:
            messages.success(request, f'Trainer "{trainer.name}" has been deactivated.')

        # Redirect back to the trainer view
        return redirect('trainers:trainer_view')


# edit a trainer


# class TrainerToggleStatus(LoginRequiredMixin, View):
#     def post(self, request, *args, **hytrewq
#         trainer = Trainer.objects.get(pk=kwargs['pk'])

#         # Toggle the trainer's status
#         if trainer.status:  # If active, trying to deactivate
#             if trainer.course_set.exists():  # Check if trainer is assigned to any course
#                 course_names = ", ".join([course.title for course in trainer.course_set.all()])
#                 messages.error(self.request, f'Trainer "{trainer.name}" is already assigned to "{course_names}". Please untag them from the course(s) to deactivate.')
#                 return redirect(reverse('trainers:trainer_view'))  # Redirect back to trainer list

#             # Deactivate the trainer
#             trainer.status = False
#             messages.success(self.request, f'Trainer "{trainer.name}" has been deactivated.')
#         else:
#             # Activate the trainer
#             trainer.status = True
#             messages.success(self.request, f'Trainer "{trainer.name}" has been activated.')

#         trainer.save()
#         return redirect(reverse('trainers:trainer_view'))  # Redirect back to the trainer list after action

class DegreeView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/Degree.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class DegreeForm(forms.ModelForm):
    class Meta:
        model = Degree
        fields = "__all__"


class DegreeAdd(FormView):
    form_class = DegreeForm
    template_name = "trainers/DegreeAdd.html"
    success_url = reverse_lazy('trainers:DegreeSuccess')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class DegreeSuccess(TemplateView):
    template_name = 'trainers/DegreeSuccess.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "A NEW DEGREE IS ADDED SUCCESSFULLY"
        return context


class DegreeList(ListView):
    template_name = "trainers/DegreeList.html"
    model = Degree
    context_object_name = "deg"


"______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"


class CollegeView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/College.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class CollegeForm(forms.ModelForm):
    class Meta:
        model = College
        fields = "__all__"


class CollegeAdd(FormView):
    form_class = CollegeForm
    template_name = "trainers/CollegeAdd.html"
    success_url = reverse_lazy("trainers:CollegeSuccess")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CollegeSuccess(TemplateView):
    template_name = "trainers/CollegeSuccess.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "A NEW COLLEGE IS ADDED SUCCESSFULLY"
        return context


class CollegeList(ListView):
    template_name = "trainers/CollegeList.html"
    model = College
    context_object_name = "clg"


"________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"


class QualificationsView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/Qualification.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class QualificationForm(forms.ModelForm):
    class Meta:
        model = Qualification
        fields = "__all__"


class QualificationAdd(FormView):
    form_class = QualificationForm
    template_name = "trainers/QualificationAdd.html"
    success_url = reverse_lazy("trainers:QualificationSuccess")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class QualificationSuccess(TemplateView):
    template_name = "trainers/QualificationSuccess.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "A QUALIFICATION IS ADDED SUCCESSFULLY"
        return context


class QualificationList(ListView):
    template_name = "trainers/QualificationList.html"
    model = Qualification
    context_object_name = "qua"


"_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________"


class OrganizationView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'trainers/Organization.html'

    # This method restricts the access to users in the 'Admin' group
    def test_func(self):
        return self.request.user.groups.filter(name='Admin').exists()


class OrganizationForm(forms.ModelForm):
    class Meta:

trainers/templates/trainers/Award.html
{% extends 'adminapp/base.html' %}
{% block content %}

<!-- start row  -->
<div class="row">
     <div class="col-12">
          <div>
               <h4 class="header-title mb-3">
                    <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / Plans /  <a href="{% url 'trainers:trainer_view' %}">Trainers</a> / Awards
                    <a href="{% url 'trainers:AwardAdd' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">ADD AWARD</button></a>
                    <a href="{% url 'trainers:AwardList' %}" ><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">VIEW AWARDS</button></a>

               </h4>
          </div>
     </div>
</div>
<!-- end row -->

<!-- row -->
<div class="row">
     <div class="col-lg-12">
          <div class="mt-3">

          </div>
     </div>
</div>

{% endblock %}

trainers/templates/trainers/AwardAdd.html
{% extends 'trainers/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div>
            <h4 class="header-title mb-3">
                <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / Plan /
                <a href="{% url 'trainers:trainer_view' %}">Trainers</a> / Award
            </h4>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-6">
        <div class="mt-3">
            <h4 class="mb-3">ADD AWARD</h4>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">ADD NEW AWARD</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

trainers/templates/trainers/AwardSuccess.html
{% extends 'adminapp/base.html' %}
{% block content %}

<!-- start row  -->
<div class="row">
     <div class="col-12">
          <div>
               <h4 class="header-title mb-3">


               </h4>
          </div>
     </div>
</div>
<!-- end row -->

<!-- row -->
<div class="row">
     <div class="col-lg-12">
          <div class="mt-3">
               <h1><strong>{{msg}}<br> THANK YOU!!!!!!</strong></h1><br>
               <a href="{% url 'adminapp:admin_home' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">GO TO HOME</button></a>
               <a href="{% url 'trainers:AwardAdd' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">ADD ONE MORE</button></a>
               <a href="{% url 'trainers:AwardList' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">VIEW AWARDS</button></a>
          </div>
     </div>
</div>

{% endblock %}

trainers/templates/trainers/CollegeSuccess.html
{% extends 'adminapp/base.html' %}
{% block content %}

<!-- start row  -->
<div class="row">
     <div class="col-12">
          <div>
               <h4 class="header-title mb-3">


               </h4>
          </div>
     </div>
</div>
<!-- end row -->

<!-- row -->
<div class="row">
     <div class="col-lg-12">
          <div class="mt-3">
               <h1><strong>{{msg}}<br> THANK YOU!!!!!!</strong></h1><br>
               <a href="{% url 'adminapp:admin_home' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">GO TO HOME</button></a>
               <a href="{% url 'trainers:CollegeAdd' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">ADD ONE MORE</button></a>
               <a href="{% url 'trainers:CollegeList' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">VIEW COLLEGES</button></a>
          </div>
     </div>
</div>

{% endblock %}

trainers/templates/trainers/DegreeAdd.html
{% extends 'trainers/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div>
            <h4 class="header-title mb-3">
                <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / Plan /
                <a href="{% url 'trainers:trainer_view' %}">Trainers</a> / Degree
            </h4>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-6">
        <div class="mt-3">
            <h4 class="mb-3">ADD DEGREE</h4>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">ADD NEW DEGREE</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

trainers/templates/trainers/Organization.html
{% extends 'adminapp/base.html' %}
{% block content %}

<!-- start row  -->
<div class="row">
     <div class="col-12">
          <div>
               <h4 class="header-title mb-3">
                    <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / Plans / <a href="{% url 'trainers:trainer_view' %}">Trainers</a> / Organizations
                    <a href="{% url 'trainers:OrganizationAdd' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">ADD ORGANIZATION</button></a>
                    <a href="{% url 'trainers:OrganizationList' %}" ><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">VIEW ORGANIZATIONS</button></a>

               </h4>
          </div>
     </div>
</div>
<!-- end row -->

<!-- row -->
<div class="row">
     <div class="col-lg-12">
          <div class="mt-3">
               <h5 class="font-14">Usage</h5>
               <p class="sub-header">Choose an option from the above navigation bar to get started</p>
          </div>
     </div>
</div>

{% endblock %}

trainers/templates/trainers/OrganizationSuccess.html
{% extends 'adminapp/base.html' %}
{% block content %}

<!-- start row  -->
<div class="row">
     <div class="col-12">
          <div>
               <h4 class="header-title mb-3">


               </h4>
          </div>
     </div>
</div>
<!-- end row -->

<!-- row -->
<div class="row">
     <div class="col-lg-12">
          <div class="mt-3">
               <h1><strong>{{msg}}<br> THANK YOU!!!!!!</strong></h1><br>
               <a href="{% url 'adminapp:admin_home' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">GO TO HOME</button></a>
               <a href="{% url 'trainers:OrganizationAdd' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">ADD ONE MORE</button></a>
               <a href="{% url 'trainers:OrganizationList' %}" style="margin-left: 10rem;"><button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">VIEW ORGANIZATIONS</button></a>

          </div>
     </div>
</div>

{% endblock %}

trainers/templates/trainers/trainers.html
{% extends 'trainers/base.html' %}

{% block content %}

<!-- start row -->
<div class="row">
	<div class="col-12">
		<div>
			<h4 class="header-title mb-3">
				<a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / Trainers
				<a href="{% url 'trainers:trainer_create' %}" style="margin-left: 10rem;">
					<button style="background-color: #458bc4; height: fit-content; width: fit-content; border-style: none; padding: 8px 10px; border-radius: 3px;">
						ADD TRAINERS
					</button>
				</a>
			</h4>
		</div>
	</div>
</div>
<!-- end row -->

<!-- row -->
<div class="row">

	<div id="deleteTrainerModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="deleteTrainerModalLabel">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="deleteTrainerModalLabel">Delete Confirmation</h5>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				</div>
				<div class="modal-body">
					<p>Are you sure want to delete Trainer - <b><span id="modalTrainer"></span></b> ?</p>
					<div class="alert alert-danger">
                        Be careful, action can't be undone!
                    </div>
				</div>
				<div class="modal-footer">
					<form id="deleteTrainerModalForm" method="post">
						{% csrf_token %}
						<button type="submit" value="Submit" class="btn btn-danger ml-3">Yes, Delete</button>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="col-lg-12">
		<div>
			<h5 class="font-14">Trainers</h5>
			<p class="sub-header">List of all Trainers and details</p>

			<div class="table-responsive">
				<table class="table table-bordered table-striped table-hover m-0">
                    <thead class="thead-theme-custom">
						<tr>
							<th>Name</th>
							<th>Qualification</th>
							<th>College</th>
							<th>Experience</th>
							<th>Training Exp.</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
                        {% if data %}
						{% for trainer in data %}
						<tr>
							<td>{{ trainer.name }}</td>
							<td>
								{% if trainer.qualifications.all %}
<!--									{{ trainer.qualifications.first.degree.title|default:"N/A" }}-->
									{% for qualification in  trainer.qualifications.all %}
<!--									{{ trainer.qualifications.first.degree.title|default:"N/A" }}-->
										{{qualification}}<br>
								{% endfor %}
								{% else %}
									N/A
								{% endif %}
							</td>
							<td>
								{{ trainer.qualifications.first.college.full_name|default:"N/A" }}
							</td>
							<td>
								{{ trainer.total_it_experience|default:"0" }} Yrs
							</td>
							<td>{{ trainer.training_exp }} Yrs</td>
							<td>{% if trainer.status %} Active {% else %} Inactive {% endif %}</td>
							<td>
								<form method="POST" action="{% url 'trainers:trainer_toggle_status' trainer.pk %}">
									{% csrf_token %}
									<input type="hidden" name="trainer_id" value="{{ trainer.id }}">
									<button
                                        class="{% if trainer.status %}
                                        btn btn-sm btn-warning btn-bordered-warning
                                        {% else %}
                                        btn btn-sm btn-success btn-bordered-success
                                        {% endif %} ml-1"
                                        type="submit" data-toggle="tooltip" data-placement="top"
                                        title="{% if trainer.status %}De-Activate{% else %}Activate{% endif %}">
                                        {% if trainer.status %}
                                            <i class="fa fa-exclamation-triangle fa-md"></i>
                                        {% else %}
                                            <i class="fa fa-check-circle fa-md"></i>
                                        {% endif %}
                                    </button>
								</form>
							</td>
						</tr>
						{% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="7" style="text-align: center;">No Trainers Available</td>
                        </tr>
                        {% endif %}
					</tbody>
				</table>
			</div>

		</div>
	</div>
</div>

{% endblock %}