MyPythonTrainer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls', namespace='userapp')),
    path('course/', include('courseapp.urls', namespace='courseapp')),
    path('trainer/', include('trainers.urls', namespace='trainers')),
    path('batch/', include('batchapp.urls', namespace='batchapp')),
    path('student/', include('studentapp.urls',namespace='studentapp')),
    path('admins/', include('adminapp.urls',namespace='adminapp')),
    path('topic/', include('topicapp.urls', namespace='topicapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('home/', views.AdminHomeView.as_view(), name='admin_home'),
    path('admin/profile/edit/', views.AdminProfileEdit.as_view(), name='admin_profile'),
    path('admin/profile/view/', views.AdminProfileView.as_view(), name='admin_view'),
]

courseapp/urls.py
from django.urls import path
from . import views

app_name = "courseapp"

urlpatterns = [
    path('', views.CoursesFormView.as_view(), name='course_create'),
    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('<int:course_id>', views.CourseDetailView.as_view(), name='each_courses'),
    path('toggle-status/<int:pk>/', views.CourseToggleStatus.as_view(), name='course_toggle_status'),
]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('adminregistration/', views.RegisterAdminView.as_view(), name='register-admin'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.NewIndexPageView.as_view(), name='home'),  # Home URL for students
    # path('home/', views.IndexPageView.as_view(), name='index_page'),  # Home URL for students
    # path('about/', views.AboutPageView.as_view(), name='about_page'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
    path('my-enrolled-courses/', views.AppliedCoursesView.as_view(), name='applied_courses'),
    path('user/profile/view', views.UserProfileView.as_view(), name='user_profile_view'),
    path('user/profile/edit', views.UserProfileEdit.as_view(), name='user_profile_edit'),

    path('view/', views.CourseListView.as_view(), name='course_view'),
    path('<int:course_id>', views.CourseDetailView.as_view(), name='each_course'),
    # path('registration/<str:course_title>/', views.CourseRegistration.as_view(), name='course_regs'),

    # JC - New UI
    path('home/', views.NewIndexPageView.as_view(), name='new_index_page'),
    path('trainers/', views.NewAboutPageView.as_view(), name='new_about_page'),
    path('courses/', views.NewCoursesPageView.as_view(), name='new_courses_page'),
    path('course-calendar/', views.NewCourseCalendarPageView.as_view(), name='new_courses_calendar_page'),
    path('stories/', views.NewStoriesPageView.as_view(), name='new_stories_page'),
    path('contact/', views.NewContactPageView.as_view(), name='new_contact_page'),
    path('privacy-policy/', views.PrivacyPolicyPageView.as_view(), name='privacy_policy'),
    path('terms-conditions/', views.TermsConditionsPageView.as_view(), name='terms_conditions'),
    path('refund-policy/', views.RefundPolicyPageView.as_view(), name='refund_policy'),
    path('register/', views.NewRegistrationPageView.as_view(), name='new_registration_page'),
    path('login/', views.NewLoginPageView.as_view(), name='login'),
    path('payment/proceed/<int:course_id>/<str:payment_type>/', views.MakePaymentView.as_view(), name='make_payment'),
    path('course/enroll/<str:course_title>/<str:batch_name>', views.EnrollCourse.as_view(), name='new_course_enrollment'),
    path('confirm_enrollment/<str:course_title>/<str:batch_name>/', views.ConfirmEnrollCourse.as_view(), name='confirm_enrollment'),
    path('payment/verify/', views.PaymentVerificationView.as_view(), name='payment_verification'),
    path('payment/failed/', views.PaymentFailedView.as_view(), name='payment_failed'),
    path('payment/success/', views.PaymentSuccessView.as_view(), name='payment_success'),
    path('batch/details/<str:batch_number>', views.BatchDetailView.as_view(), name='batch_details'),
    path('feedback/',views.CourseFeedbackCreateView.as_view(),name='feedback'),
    path('feedbackSuccess/',views.FeedbackSuccessView.as_view(),name='feedback-success'),
    path('feedbackList/',views.CourseFeedbackListView.as_view(),name='feedback-List'),
]

courseapp/models.py
from django.db import models
from django.conf import settings
import os
from django import forms
from django.forms import ModelForm
from trainers.models import Trainer
from topicapp.models import Topic
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator 

# Create your models here.

def get_image_choices():
        # Define the directory where images are stored
        image_folder = os.path.join(settings.MEDIA_ROOT, 'images')
        image_files = []

        # Get a list of image files from the folder
        if os.path.exists(image_folder):
            for filename in os.listdir(image_folder):
                if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                    # Store the filename as a tuple (file, file)
                    image_files.append((f'images/{filename}', filename))
        return image_files

class Course(models.Model):
    title = models.CharField(max_length=40, unique=True)
    description = models.TextField(max_length=1000)
    topic = models.ManyToManyField(Topic, blank=False)
    duration = models.PositiveIntegerField(verbose_name='Duration (days)', default=0, validators=[MinValueValidator(30), MaxValueValidator(200)])
    trainers = models.ManyToManyField(Trainer, verbose_name="Trainers")
    fees = models.PositiveIntegerField(verbose_name="Course Fee (Rs.)", validators=[MinValueValidator(5000), MaxValueValidator(80000)])
    uploaded_file = models.FileField(verbose_name='Course Content', upload_to='documents/')
    image = models.CharField(max_length=255, choices=get_image_choices())
    status = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        super(Course, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('course_update', kwargs={'pk': self.pk})


class CourseForm(ModelForm):
    class Meta:
        uploaded_file = forms.FileField(
        required=False,
         label='Course Content'
        )
        
        model = Course
        fields = '__all__'
        exclude = ['status']

        widgets = {
            'description': forms.Textarea(attrs={'rows': 5, 'cols': 40}),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Populate the 'topics' field with active topics
        self.fields['topic'].queryset = Topic.objects.filter(status=True)
        self.fields['trainers'].queryset = Trainer.objects.filter(status=True)
        # print(Trainer.objects.filter(status=True))

courseapp/views.py
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from .models import Course, CourseForm
from django.views.generic import View, UpdateView, DeleteView, FormView, ListView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class CoursesFormView(LoginRequiredMixin,FormView):
    form_class = CourseForm
    template_name = 'courseapp/course.html' 
    success_url = reverse_lazy('courseapp:course_list')
    login_url = '/login/'

    def form_valid(self, form):
        course = form.save(commit=False)
        # print(course.topic)
        
        if 'uploaded_file' in self.request.FILES:
            uploaded_file = self.request.FILES['uploaded_file']
            course_title_clean = course.title.replace(' ', '_').lower() 
            filename = f"{course_title_clean}_{uploaded_file.name}"
            
            # Assign the custom filename to the uploaded file field
            course.uploaded_file.save(filename, uploaded_file)

        course.save()  # Save the course with the file
        # print("Selected topics:", form.cleaned_data.get('topic'))

        topics = form.cleaned_data.get('topic')  # Retrieve selected topics from the form
        if topics:
            course.topic.set(topics)

        trainers = form.cleaned_data.get('trainers')  # Retrieve selected topics from the form
        if trainers:
            course.trainers.set(trainers)
        
        num = course.title
        messages.success(self.request, f'{num} course created successfully')
        return super().form_valid(form)
    
# course list
class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'courseapp/courselist.html'
    context_object_name = 'course'

    def post(self, request, *args, **kwargs):
        # Handle the status change when a checkbox is toggled
        course_id = request.POST.get('course_id')
        course = get_object_or_404(Course, id=course_id)
        course.status = not course.status  # Toggle the status
        course.save()

        # Redirect to the same page after the status is toggled
        return redirect('courseapp:course_list') 
    
    def get_queryset(self):
        queryset = super().get_queryset().all().order_by('title')
        return queryset
    
# each courses
class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'courseapp/course_details.html'
    context_object_name = 'each_one'

    def get_object(self):
        course_id = self.kwargs.get('course_id')
        return get_object_or_404(Course, pk=course_id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

# delete a course

class CourseToggleStatus(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        course = Course.objects.get(pk=self.kwargs['pk'])
        if course.batch_set.exists():
            batch_names = ", ".join([batch.batch_number for batch in course.batch_set.all()])
            messages.error(request, f'One or more batches ({batch_names}) are created and/or opened registrations for "{course.title}". You can\'t deactivate the course now.')
            return redirect('courseapp:course_list')  # Redirect back to the trainer view page
        course.status = not course.status
        course.save()
        if course.status:
            messages.success(request, f'Course "{course.title}" has been activated.')
        else:
            messages.success(request, f'Course "{course.title}" has been deactivated.')
        return redirect('courseapp:course_list')
    
# update a course

courseapp/templates/courseapp/_not_used_course_confirm_delete.html
{% extends 'courseapp/base.html' %}
{% block content%}

<!-- USED -->
<!-- start row  -->
<div class="row">
    <div class="col-12">
        <div>
            <h4 class="header-title">
                <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / <a
                    href="{% url 'courseapp:course_list' %}">Course</a> / Add Course
            </h4>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-6">
        <div class="mt-3">
            <h4 class="mb-3">Delete Confirmation</h4>
            <form method="post">
                {% csrf_token %}
                <p class="text-secondary">Are you sure want to delete <b>Course "{{object.title}}"</b> ?</p>
                <a href="{% url 'courseapp:course_list' %}" class="btn btn-success">Go Back to Courses</a>
                <button type="submit" value="Submit" class="btn btn-danger ml-3">Yes, Delete</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

courseapp/templates/courseapp/_not_used_course_details.html
{% extends 'courseapp/base.html' %}

{% load humanize %}
{% block content %}

{% if each_one %}

<!-- NOT USED -->

<div class="container">
    <div class="row mb-5 fields mt-5">
        <div class="col-md-6">
            <section id="bc" class="mb-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'adminapp:admin_home' %}">Admin Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="{% url 'courseapp:course_list' %}">Courses</a>
                        </li>

                        <li class="breadcrumb-item active" aria-current="page">
                            {{each_one.name}}
                        </li>
                    </ol>
                </nav>
            </section>
            <ul class="list-group list-group-flush">
                <h3 class="text-info">Course Info</h3>

                <li class="list-group-item text-secondary">
                    Course Code:
                   <span class="float-right">{{each_one.code}}</span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Course Name:
                   <span class="float-right">{{each_one.name}}</span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Duration:
                   <span class="float-right">{{each_one.duration}}</span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Fees:
                   <span class="float-right">{{each_one.fees|intcomma}}
                   </span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Trainer:
 
                   <span class="float-right">{{each_one.trainer}}
                   </span>
                 </li>
                 <li class="list-group-item text-secondary">
                     Status:
  
                    <span class="float-right">{{each_one.status}}
                    </span>
                  </li>
            </ul>
            <div class="pt-4">
                <a href="{% url 'courseapp:course_edit' each_one.id %}" class="btn btn-secondary float-left px-4">Update</a>
                <a href="{% url 'courseapp:course_delete' each_one.id %}" class="btn btn-danger float-right px-4">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endblock %}

courseapp/templates/courseapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>My Python Trainer | Course App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="My Python Trainer | Admin Panel" name="description" />
    <meta content="JC Web Technologies" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'frontend_assets/images/favicon.ico' %}">
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"
        id="bootstrap-stylesheet" />
    <link href="{% static 'assets/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'assets/css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet" />
    <style>
        .alert-error, .text-error {
            color: #842029
        }
    
        .alert-error {
            background-color: #f8d7da;
            border-color: #f5c2c7
        }
    </style>
</head>

<body data-layout="horizontal">
    <div id="wrapper">
        <!--navbar-->
        {% include 'partial/_admin-navbar.html' %}

        <div class="content-page">
            <div class="content">

                <!-- Start container-fluid -->
                <div class="container-fluid">

                    <!-- Messages start -->
                    {% if messages %}
                    <div class="row">
                        <div class="col-lg-8">
                            {% for msg in messages %}
                            <div class="alert alert-{{msg.tags}} text-{{msg.tags}} alert-dismissible fade show"
                                role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                                {{msg}}
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    <!-- Messages end -->

                    {% block content%}
                    {% endblock %}

                    {% include 'partial/_admin-footer.html' %}
                </div>
            </div>

        </div>
    </div>
    <script src="{% static 'assets/js/vendor.min.js' %}"></script>
    <script src="{% static 'assets/js/app.min.js' %}"></script>
    
    {% if request.resolver_match.url_name == 'course_list' %}
    <script>
        // Courses delete
        $(document).ready(function () {
            $('.delete-course-modal').on('click', function () {
                $('#modalCourse').text($(this).data('course'));
                $('#deleteCourseModalForm').attr('action', $(this).data('course-delete-action'));
                $('#deleteCourseModal').modal('show');
            });
        });
    </script>
    {% endif %}
    <script>
        $('#adminLogoutBtn').on('click', function (e) { e.preventDefault(); $('#adminLogoutForm').submit(); });
        
        $(document).ready(function () {
            $('#id_topic').on('change', function () {
                let totalDays = 0;
                $('#id_topic option:selected').each(function () {
                    let text = $(this).text();
                    let days = text.match(/\((\d+) days\)/);
                    if (days) {
                        totalDays += parseInt(days[1]);
                    }
                });
                $('#id_duration').val(totalDays);
            });
        });
    </script>
</body>

</html>

courseapp/templates/courseapp/course.html
{% extends 'courseapp/base.html'%}

{% load crispy_forms_tags %}

{% block content%}

<div class="row">
    <div class="col-12">
        <div>
            <h4 class="header-title">
                <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / <a
                    href="{% url 'courseapp:course_list' %}">Course</a> / Add Course
            </h4>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-6">
        <div class="mt-3">
            <h4 class="mb-3">Add Course</h4>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <!-- create a legend -->
                    <!-- <legend class="border-bottom mb-4">
                        Add batch
                    </legend> -->
                    {{form|crispy}}
                </fieldset>
                <!-- create a button -->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Add New Course</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock%}

courseapp/templates/courseapp/course_confirm_delete.html
{% extends 'courseapp/base.html' %}
{% block content%}

<!-- USED -->
<!-- start row  -->
<div class="row">
    <div class="col-12">
        <div>
            <h4 class="header-title">
                <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / <a
                    href="{% url 'courseapp:course_list' %}">Course</a> / Add Course
            </h4>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-6">
        <div class="mt-3">
            <h4 class="mb-3">Delete Confirmation</h4>
            <form method="post">
                {% csrf_token %}
                <p class="text-secondary">Are you sure want to delete <b>Course "{{object.title}}"</b> ?</p>
                <a href="{% url 'courseapp:course_list' %}" class="btn btn-success">Go Back to Courses</a>
                <button type="submit" value="Submit" class="btn btn-danger ml-3">Yes, Delete</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

courseapp/templates/courseapp/course_details.html
{% extends 'courseapp/base.html' %}

{% load humanize %}
{% block content %}

{% if each_one %}

<!-- NOT USED -->

<div class="container">
    <div class="row mb-5 fields mt-5">
        <div class="col-md-6">
            <section id="bc" class="mb-5">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'adminapp:admin_home' %}">Admin Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="{% url 'courseapp:course_list' %}">Courses</a>
                        </li>

                        <li class="breadcrumb-item active" aria-current="page">
                            {{each_one.name}}
                        </li>
                    </ol>
                </nav>
            </section>
            <ul class="list-group list-group-flush">
                <h3 class="text-info">Course Info</h3>

                <li class="list-group-item text-secondary">
                    Course Code:
                   <span class="float-right">{{each_one.code}}</span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Course Name:
                   <span class="float-right">{{each_one.name}}</span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Duration:
                   <span class="float-right">{{each_one.duration}}</span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Fees:
                   <span class="float-right">{{each_one.fees|intcomma}}
                   </span>
                 </li>
                 <li class="list-group-item text-secondary">
                    Trainer:
 
                   <span class="float-right">{{each_one.trainer}}
                   </span>
                 </li>
                 <li class="list-group-item text-secondary">
                     Status:
  
                    <span class="float-right">{{each_one.status}}
                    </span>
                  </li>
            </ul>
        </div>
    </div>
</div>

{% endif %}

{% endblock %}

courseapp/templates/courseapp/course_form.html
{% extends 'courseapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- start row  -->
<div class="row">
    <div class="col-12">
        <div>
            <h4 class="header-title mb-3">
                <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / <a
                    href="{% url 'courseapp:course_list' %}">Courses</a> / Edit Course
            </h4>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-6">
        <div class="mt-3">
            <h4 class="mb-3">Update Course</h4>
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <div class="form-group">
                    <button type="submit" class="btn btn-success btn-block">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

courseapp/templates/courseapp/courselist.html
{% extends 'courseapp/base.html' %}
{% load humanize %}
{% load custom_filters %}
{% block content %}

<!-- start row  -->
<div class="row">
    <div class="col-12">
        <div>
            <h4 class="header-title mb-3">
                <a href="{% url 'adminapp:admin_home' %}">Admin Home</a> / Courses
            </h4>
        </div>
    </div>
</div>
<!-- end row -->

<!-- row -->
<div class="row">

    <!-- DELETE MODAL -->
    <!-- ... Keep this section unchanged ... -->

    <div class="col-lg-12">
        <div class="mt-3">
            <h5 class="font-14">Courses</h5>
            <p class="sub-header">List of all course and details</p>

            <!-- Export Buttons -->
            <div class="d-flex justify-content-end mb-2">
                <button class="btn btn-outline-success btn-sm mr-2" onclick="exportTableToExcel('courseTable')">
                    📊 Export Excel
                </button>
                <button class="btn btn-outline-danger btn-sm" onclick="exportTableToPDF('courseTable')">
                    📄 Export PDF
                </button>
            </div>

            <!-- Table -->
            <div class="table-responsive">
                <table id="courseTable" class="table table-bordered table-striped table-hover m-0">
                    <thead class="thead-theme-custom">
                        <tr>
                            <th>Title</th>
                            <th>Duration (months)</th>
                            <th>Trainers</th>
                            <th>Topics</th>
                            <th>Fees (in Rs.)</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if course %}
                        {% for each in course %}
                        <tr>
                            <td>{{ each.title }}</td>
                            <td>{{ each.duration|course_duration_round }}</td>
                            <td>
                                {% for trainer in each.trainers.all %}
                                    {{ trainer.name }} <br>
                                    <span style="font-size: 0.8em;">
                                    <b>{{ trainer.title }} </b><br>
                                    <b>{{ trainer.training_exp }} yrs</b> Experience
                                    </span>
                                    {% if not forloop.last %}<br><br>{% endif %}
                                {% empty %}
                                    No trainers available
                                {% endfor %}
                            </td>
                            <td>{% for topic in each.topic.all %}
                                {{ topic.topic_name }} {% if not forloop.last %}<br>{% endif %}
                            {% empty %}
                                No topics available
                            {% endfor %}
                            </td>
                            <td>&#8377;{{ each.fees|intcomma}}/-</td>
                            <td>{% if each.status %} Active {% else %} Inactive {% endif %}</td>
                            <td>
                                <form method="post" action="{% url 'courseapp:course_toggle_status' each.pk %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="course_id" value="{{ each.id }}">
                                    <a href="{{ each.uploaded_file.url }}" target="_blank" rel="noopener noreferrer">
                                        <button type="button" class="btn btn-danger btn-sm" title="Course Content">
                                            <i class="fa fa-file-pdf fa-lg"></i>
                                        </button>
                                    </a>
                                    <button
                                        class="{% if each.status %}btn btn-sm btn-warning btn-bordered-warning{% else %}btn btn-sm btn-success btn-bordered-success{% endif %} ml-1"
                                        type="submit" title="{% if each.status %}De-Activate{% else %}Activate{% endif %}">
                                        {% if each.status %}
                                            <i class="fa fa-exclamation-triangle fa-md"></i>
                                        {% else %}
                                            <i class="fa fa-check-circle fa-md"></i>
                                        {% endif %}
                                    </button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="7" style="text-align: center;">No Courses Available</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<!-- Excel + PDF Export Libraries -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.28/jspdf.plugin.autotable.min.js"></script>

<script>
function exportTableToExcel(tableID, filename = 'Courses.xlsx') {
    const table = document.getElementById(tableID);
    const wb = XLSX.utils.table_to_book(table, {sheet: "Courses"});
    XLSX.writeFile(wb, filename);
}

function exportTableToPDF(tableID, filename = 'Courses.pdf') {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const table = document.getElementById(tableID);
    let rows = [], headers = [];

    // Header
    table.querySelectorAll("thead tr th").forEach(th => headers.push(th.innerText));

    // Body rows
    table.querySelectorAll("tbody tr").forEach(row => {
        let rowData = [];
        row.querySelectorAll("td").forEach(td => rowData.push(td.innerText.trim()));
        rows.push(rowData);
    });

    doc.autoTable({
        head: [headers],
        body: rows,
        theme: 'grid',
        headStyles: { fillColor: [22, 160, 133] },
        styles: { fontSize: 8 },
        margin: { top: 20 }
    });

    doc.save(filename);
}
</script>

{% endblock %}

courseapp/templates/courseapp/edit_details.html
{% extends 'courseapp/base.html' %}
{% load crispy_form_tags%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST">
                {% csrf_token %}

                <fieldset class="form-group">
                    <h1 class="display-4">Edit Course</h1>
                    {{form|crispy}}
                </fieldset>
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-secondary">Save</button>
                </div>
            </form>
        </div>
    </div>

</div>

{% endblock %}