MyPythonTrainer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls', namespace='userapp')),
    path('course/', include('courseapp.urls', namespace='courseapp')),
    path('trainer/', include('trainers.urls', namespace='trainers')),
    path('batch/', include('batchapp.urls', namespace='batchapp')),
    path('student/', include('studentapp.urls',namespace='studentapp')),
    path('admins/', include('adminapp.urls',namespace='adminapp')),
    path('topic/', include('topicapp.urls', namespace='topicapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from . import views

app_name = 'adminapp'

urlpatterns = [
    path('home/', views.AdminHomeView.as_view(), name='admin_home'),
    path('admin/profile/edit/', views.AdminProfileEdit.as_view(), name='admin_profile'),
    path('admin/profile/view/', views.AdminProfileView.as_view(), name='admin_view'),
]

batchapp/urls.py
from django.urls import path
from . import views

app_name = "batchapp"

urlpatterns = [
    path('', views.BatchFormView.as_view(), name='batch'),
    path('batches/', views.BatchListView.as_view(), name='batch_list'),
    path('<int:batch_id>', views.BatchDetailView.as_view(), name='each_batch'),
    path('delete/<int:pk>', views.BatchDelete.as_view(), name='batch_delete'),
    path('edit/<int:pk>', views.BatchEdit.as_view(), name='edit_batch'),
]

topicapp/urls.py
from django.urls import path
from . import views

app_name = "topicapp"
urlpatterns = [
    path('', views.TopicFormView.as_view(), name='topic'),
    path('topics/', views.TopicListView.as_view(), name='topic_list'),
    path('<int:topic_id>', views.TopicDetailView.as_view(), name='each_topic'),
    path('toggle-status/<int:pk>/', views.TopicToggleStatus.as_view(), name='topic_toggle_status'),
]

trainers/urls.py
from django.urls import path
from . import views

app_name = "trainers"
urlpatterns = [
    path('', views.TrainerFormView.as_view(), name='trainer_create'),
    path('trainers/', views.TrainersListView.as_view(), name='trainer_view'),
    path('Degree/', views.DegreeView.as_view(), name='Degree'),
    path('DegreeAdd/', views.DegreeAdd.as_view(), name='DegreeAdd'),
    path('DegreeSuccess/', views.DegreeSuccess.as_view(), name='DegreeSuccess'),
    path('DegreeList/', views.DegreeList.as_view(), name='DegreeList'),
    path('College/', views.CollegeView.as_view(), name='College'),
    path('CollegeAdd/', views.CollegeAdd.as_view(), name='CollegeAdd'),
    path('CollegeSuccess/', views.CollegeSuccess.as_view(), name='CollegeSuccess'),
    path('CollegeList/', views.CollegeList.as_view(), name='CollegeList'),
    path('Qualification/', views.QualificationsView.as_view(), name='Qualification'),
    path('QualificationAdd/', views.QualificationAdd.as_view(), name='QualificationAdd'),
    path('QualificationSuccess/', views.QualificationSuccess.as_view(), name='QualificationSuccess'),
    path('QualificationList/', views.QualificationList.as_view(), name='QualificationList'),
    path('Organization/', views.OrganizationView.as_view(), name='Organization'),
    path('OrganizationAdd/', views.OrganizationAdd.as_view(), name='OrganizationAdd'),
    path('OrganizationSuccess/', views.OrganizationSuccess.as_view(), name='OrganizationSuccess'),
    path('OrganizationList/', views.OrganizationList.as_view(), name='OrganizationList'),
    path('Award/', views.AwardsView.as_view(), name='Award'),
    path('AwardAdd/', views.AwardAdd.as_view(), name='AwardAdd'),
    path('AwardSuccess/', views.AwardSuccess.as_view(), name='AwardSuccess'),
    path('AwardList/', views.AwardList.as_view(), name='AwardList'),
    path('<int:trainer_id>', views.TrainerDetailView.as_view(), name='trainer_one'),
    path('toggle-status/<int:pk>/', views.TrainerToggleStatus.as_view(), name='trainer_toggle_status'),
    path('stories/',views.CourseFeedbackListView.as_view(),name='stories'),
    path('feedback/approve/<int:feedback_id>/', views.approve_feedback, name='approve_feedback'),
    path('feedback/reject/<int:feedback_id>/', views.reject_feedback, name='reject_feedback'),

]

userapp/urls.py
# userapp/urls.py

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'
urlpatterns = [
    path('adminregistration/', views.RegisterAdminView.as_view(), name='register-admin'),
    path('logout/', auth_views.LogoutView.as_view(template_name='userapp/logout.html'), name='logout'),
    path('no-access/', views.TemplateView.as_view(template_name='userapp/no_access.html'), name='no-access'),

    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', views.NewIndexPageView.as_view(), name='home'),  # Home URL for students
    # path('home/', views.IndexPageView.as_view(), name='index_page'),  # Home URL for students
    # path('about/', views.AboutPageView.as_view(), name='about_page'),
    # path('contact/', views.ContactView.as_view(), name='contact'),
    path('my-enrolled-courses/', views.AppliedCoursesView.as_view(), name='applied_courses'),
    path('user/profile/view', views.UserProfileView.as_view(), name='user_profile_view'),
    path('user/profile/edit', views.UserProfileEdit.as_view(), name='user_profile_edit'),

    path('view/', views.CourseListView.as_view(), name='course_view'),
    path('<int:course_id>', views.CourseDetailView.as_view(), name='each_course'),
    # path('registration/<str:course_title>/', views.CourseRegistration.as_view(), name='course_regs'),

    # JC - New UI
    path('home/', views.NewIndexPageView.as_view(), name='new_index_page'),
    path('trainers/', views.NewAboutPageView.as_view(), name='new_about_page'),
    path('courses/', views.NewCoursesPageView.as_view(), name='new_courses_page'),
    path('course-calendar/', views.NewCourseCalendarPageView.as_view(), name='new_courses_calendar_page'),
    path('stories/', views.NewStoriesPageView.as_view(), name='new_stories_page'),
    path('contact/', views.NewContactPageView.as_view(), name='new_contact_page'),
    path('privacy-policy/', views.PrivacyPolicyPageView.as_view(), name='privacy_policy'),
    path('terms-conditions/', views.TermsConditionsPageView.as_view(), name='terms_conditions'),
    path('refund-policy/', views.RefundPolicyPageView.as_view(), name='refund_policy'),
    path('register/', views.NewRegistrationPageView.as_view(), name='new_registration_page'),
    path('login/', views.NewLoginPageView.as_view(), name='login'),
    path('payment/proceed/<int:course_id>/<str:payment_type>/', views.MakePaymentView.as_view(), name='make_payment'),
    path('course/enroll/<str:course_title>/<str:batch_name>', views.EnrollCourse.as_view(), name='new_course_enrollment'),
    path('confirm_enrollment/<str:course_title>/<str:batch_name>/', views.ConfirmEnrollCourse.as_view(), name='confirm_enrollment'),
    path('payment/verify/', views.PaymentVerificationView.as_view(), name='payment_verification'),
    path('payment/failed/', views.PaymentFailedView.as_view(), name='payment_failed'),
    path('payment/success/', views.PaymentSuccessView.as_view(), name='payment_success'),
    path('batch/details/<str:batch_number>', views.BatchDetailView.as_view(), name='batch_details'),
    path('feedback/',views.CourseFeedbackCreateView.as_view(),name='feedback'),
    path('feedbackSuccess/',views.FeedbackSuccessView.as_view(),name='feedback-success'),
    path('feedbackList/',views.CourseFeedbackListView.as_view(),name='feedback-List'),
]

templates/partial/_admin-footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                &copy; 2024 My Python Trainer (⚡ by <a
                href="https://jcwebtechnologies.com/?ref=mypyt_footer" target="_blank">JCWT</a> )</a>
            </div>
        </div>
    </div>
</footer>

templates/partial/_admin-navbar.html
{% load static %}
<header id="topnav">
    <!-- Topbar Start -->
    <div class="navbar-custom">
        <div class="container-fluid">
            <ul class="list-unstyled topnav-menu float-right mb-0">

                <li class="dropdown notification-list">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle nav-link">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </li>

                {% if user.is_authenticated %}
                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle nav-user mr-0" data-toggle="dropdown" href="#" role="button"
                        aria-haspopup="false" aria-expanded="false">
                        <img src="{% static 'assets/images/users/profile-user.jpg' %}" alt="user-image"
                            class="rounded-circle">
                        <span class="pro-user-name d-none d-xl-inline-block ml-2">
                            {{ user.first_name }} {{ user.last_name }}
                            <i class="mdi mdi-chevron-down"></i></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <!--<a href="javascript:void(0);" class="dropdown-item notify-item">
                            <i class="mdi mdi-account-outline"></i>
                            <span>Profile</span>
                        </a> -->
                        <a href="{% url 'adminapp:admin_view' %}" class="dropdown-item notify-item">
                            <i class="mdi mdi-account"></i>
                            <span>My Profile</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item notify-item" id="adminLogoutBtn">
                            <i class="mdi mdi-logout-variant"></i>
                            <span>Logout</span>
                        </a>
                        <form method="POST" action="{% url 'userapp:logout' %}" style="display:inline;" id="adminLogoutForm">
                            {% csrf_token %}
                            <!--<button type="submit" class="dropdown-item notify-item" style="background: none; border: none; color: inherit; padding: 0; font: inherit;">
                                <i class="mdi mdi-logout-variant"></i>
                                <span>Logout</span>
                            </button>-->
                        </form>
                    </div>
                </li>
                {% else %}
                <li class="dropdown notification-list">
                    <a href="{% url 'userapp:login' %}" class="nav-link">
                        <i class="mdi mdi-login"></i>
                        <span>Login</span>
                    </a>
                </li>
                <li class="dropdown notification-list">
                    <a href="{% url 'userapp:register-admin' %}" class="nav-link">
                        <i class="mdi mdi-account-plus"></i>
                        <span>Register</span>
                    </a>
                </li>
                {% endif %}
            </ul>

            <!-- LOGO -->
            <div class="logo-box">
                <a href="{% url 'adminapp:admin_home' %}" class="logo text-center">
                    <span class="logo-lg">
                        <!-- <span class="logo-lg-text-light">My Python Trainer</span> -->
                        <img src="{% static 'frontend_assets/images/logo-1.png' %}" alt="My Python Trainer"
                        style="padding: 2px;" height="45">
                    </span>
                    <span class="logo-sm">
                        <!-- <img src="{% static 'assets/images/logo-sm.png' %}" alt="" height="22"> -->
                        <img src="{% static 'frontend_assets/images/logo-1.png' %}" alt="My Python Trainer"
                        style="padding: 2px;" height="45">
                    </span>
                </a>
            </div>

            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu">

                    <li>
                        <a href="{% url 'adminapp:admin_home' %}">
                            <i class="ti-home"></i>Home
                        </a>
                    </li>

                    {% if user.is_authenticated %}
<!--                    <li class="has-submenu">-->
<!--                        <a href="{% url 'batchapp:batch_list' %}"><i class="mdi mdi-account-multiple"></i>Batches</a>-->
<!--                        <ul class="submenu">-->
<!--                            <li><a href="{% url 'batchapp:batch' %}">Add New Batch</a></li>-->
<!--                            <li><a href="{% url 'batchapp:batch_list' %}">View All Batches</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
                    <li class="has-submenu">
                        <a href="{% url 'batchapp:batch_list' %}"><i class="mdi mdi-account-multiple"></i> Plan</a>
                        <ul class="submenu">
                            <li class="has-submenu">
                                <a href="#">Topics</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'topicapp:topic' %}">Add New Topic</a></li>
                                    <li><a href="{% url 'topicapp:topic_list' %}">View All Topics</a></li>
                                </ul>
                            </li>
                            <li class="has-submenu">
                                <a href="{% url 'trainers:trainer_view' %}">Trainers</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'trainers:Degree' %}">Degree</a></li>
                                    <li><a href="{% url 'trainers:College' %}">Colleges</a></li>
                                    <li><a href="{% url 'trainers:Qualification' %}">Qualifications</a></li>
                                    <li><a href="{% url 'trainers:Organization' %}">Organisations</a></li>
                                    <li><a href="{% url 'trainers:Award' %}">Awards</a></li>
                                </ul>
                            </li>
                            <li class="has-submenu">
                                <a href="#">Courses</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'courseapp:course_create' %}">Add New Course</a></li>
                                    <li><a href="{% url 'courseapp:course_list' %}">View All Courses</a></li>
                                </ul>
                            </li>
                            <li class="has-submenu">
                                <a href="#">Batches</a>
                                <ul class="submenu">
                                    <li><a href="{% url 'batchapp:batch' %}">Add New Batch</a></li>
                                    <li><a href="{% url 'batchapp:batch_list' %}">View All Batches</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>


<!--                    <li class="has-submenu">-->
<!--                        <a href="{% url 'courseapp:course_list' %}"><i class="ti-book"></i>Courses</a>-->
<!--                        <ul class="submenu">-->
<!--                            <li><a href="{% url 'courseapp:course_create' %}">Add New Course</a></li>-->
<!--                            <li><a href="{% url 'courseapp:course_list' %}">View All Courses</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->
                          <li class="has-submenu">
                            <a href="{% url 'courseapp:course_list' %}"><i class="ti-book"></i>Students</a>
                            <ul class="submenu">
                                <li><a href="{% url 'trainers:stories' %}">Stories</a></li>
                                <li><a href="{% url 'studentapp:view_registrations' %}">Registrations</a></li>
                                <li><a href="{% url 'studentapp:view_students' %}">Enrollments</a></li>
                            </ul>
                        </li>

<!--                    <li class="has-submenu">-->
<!--                        <a href="{% url 'topicapp:topic_list' %}"><i class="ti-bookmark"></i>Topics</a>-->
<!--                        <ul class="submenu">-->
<!--                            <li><a href="{% url 'topicapp:topic' %}">Add New Topic</a></li>-->
<!--                            <li><a href="{% url 'topicapp:topic_list' %}">View All Topics</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->

                    <li class="has-submenu">
                        <a href=""><i class="ti-user"></i>Staff</a>
                    </li>


<!--					<li class="has-submenu">-->
<!--                        <a href="{% url 'studentapp:view_students' %}"><i class="ti-user"></i>Registrations</a>-->
<!--                        <ul class="submenu">-->
<!--                            <li><a href="{% url 'studentapp:view_registrations' %}">All Students</a></li>-->
<!--                            <li><a href="{% url 'studentapp:view_students' %}">All Enrollments</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->

					<!--
                    <li>
                        <a href="{% url 'studentapp:view_students' %}">History</a>
                    </li> -->
                    {% endif %}

                </ul>
                <!-- End navigation menu -->
                <div class="clearfix"></div>
            </div>
            <!-- end #navigation -->
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- end Topbar -->
</header>
<style>
    .table .thead-theme-custom th {
        color: #ffffff;
        background-color: #3db9dc;
        border-color: #dee2e6;
    }
</style>

templates/partial/_navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href="{% url 'userapp:index_page' %}" class="navbar-brand">Course Registration</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"></li>
        <a href="{% url 'userapp:home' %}" class="nav-link">My Home
        </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'userapp:course_view' %}" class="nav-link">Courses
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'userapp:about_page' %}" class="nav-link">About Us
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"></li>
          <a href="{% url 'userapp:applied_courses' %}" class="nav-link">My Applied Courses
          </a>
        </li>

        <li class="nav-item">
          <a href="{% url 'userapp:logout' %}" class="nav-link">
            Logout
          </a>
        </li>
        
        {% else %}

        <li class="nav-item">
          <a href="{% url 'userapp:register-student' %}" class="nav-link">
            Register
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'userapp:login' %}" class="nav-link">
            Login
          </a>
        </li>

        {% endif %}




      </ul>
    </div>
  </div>
</nav>

templates/partial/_navbarhr.html
{% load static %}
<header id="topnav">
    <!-- Topbar Start -->
    <div class="navbar-custom">
        <div class="container-fluid">
            <ul class="list-unstyled topnav-menu float-right mb-0">

                <li class="dropdown notification-list">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle nav-link">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </li>

                {% if user.is_authenticated %}
                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle nav-user mr-0" data-toggle="dropdown" href="#" role="button"
                        aria-haspopup="false" aria-expanded="false">
                        <img src="{% static 'assets/images/users/profile-user.jpg' %}" alt="user-image"
                            class="rounded-circle">
                        <span class="pro-user-name d-none d-xl-inline-block ml-2">Admin<i
                                class="mdi mdi-chevron-down"></i></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <!--<a href="javascript:void(0);" class="dropdown-item notify-item">
                            <i class="mdi mdi-account-outline"></i>
                            <span>Profile</span>
                        </a> -->
                        <a href="{% url 'adminapp:admin_profile' %}" class="dropdown-item notify-item">
                            <i class="mdi mdi-account"></i>
                            <span>My Profile</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item notify-item" id="adminLogoutBtn">
                            <i class="mdi mdi-logout-variant"></i>
                            <span>Logout</span>
                        </a>
                        <form method="POST" action="{% url 'userapp:logout' %}" style="display:inline;" id="adminLogoutForm">
                            {% csrf_token %}
                            <!--<button type="submit" class="dropdown-item notify-item" style="background: none; border: none; color: inherit; padding: 0; font: inherit;">
                                <i class="mdi mdi-logout-variant"></i>
                                <span>Logout</span>
                            </button>-->
                        </form>
                    </div>
                </li>
                {% else %}
                <li class="dropdown notification-list">
                    <a href="{% url 'userapp:login' %}" class="nav-link">
                        <i class="mdi mdi-login"></i>
                        <span>Login</span>
                    </a>
                </li>
                <li class="dropdown notification-list">
                    <a href="{% url 'userapp:register-admin' %}" class="nav-link">
                        <i class="mdi mdi-account-plus"></i>
                        <span>Register</span>
                    </a>
                </li>
                {% endif %}
            </ul>

            <!-- LOGO -->
            <div class="logo-box">
                <a href="{% url 'adminapp:admin_home' %}" class="logo text-center">
                    <span class="logo-lg">
                        <span class="logo-lg-text-light">My Python Trainer</span>
                    </span>
                    <span class="logo-sm">
                        <img src="{% static 'assets/images/logo-sm.png' %}" alt="" height="22">
                    </span>
                </a>
            </div>

            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu">

                    <li>
                        <a href="{% url 'adminapp:admin_home' %}">
                            <i class="ti-home"></i>Home
                        </a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="has-submenu">
                        <a href="{% url 'batchapp:batch_list' %}"><i class="mdi mdi-account-multiple"></i>Batches</a>
                        <ul class="submenu">
                            <li><a href="{% url 'batchapp:batch' %}">Add New Batch</a></li>
                            <li><a href="{% url 'batchapp:batch_list' %}">View All Batches</a></li>
                        </ul>
                    </li>

                    <li class="has-submenu">
                        <a href="{% url 'courseapp:course_list' %}"><i class="ti-book"></i>Courses</a>
                        <ul class="submenu">
                            <li><a href="{% url 'courseapp:course_create' %}">Add New Course</a></li>
                            <li><a href="{% url 'courseapp:course_list' %}">View All Courses</a></li>
                        </ul>
                    </li>

                    <li class="has-submenu">
                        <a href="{% url 'topicapp:topic_list' %}"><i class="ti-bookmark"></i>Topics</a>
                        <ul class="submenu">
                            <li><a href="{% url 'topicapp:topic' %}">Add New Topic</a></li>
                            <li><a href="{% url 'topicapp:topic_list' %}">View All Topics</a></li>
                        </ul>
                    </li>

                    <li class="has-submenu">
                        <a href="{% url 'trainers:trainer_view' %}"><i class="ti-user"></i>Trainers</a>
                        <ul class="submenu">
                            <li><a href="{% url 'trainers:trainer_create' %}">Add New Trainer</a></li>
                            <li><a href="{% url 'trainers:trainer_view' %}">View All Trainers</a></li>
                        </ul>
                    </li>

                    <li>
                        <a href="{% url 'studentapp:view_students' %}">Students & Payment History</a>
                    </li>
                    {% endif %}

                </ul>
                <!-- End navigation menu -->
                <div class="clearfix"></div>
            </div>
            <!-- end #navigation -->
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- end Topbar -->
</header>
<style>
    .table .thead-theme-custom th {
        color: #ffffff;
        background-color: #3db9dc;
        border-color: #dee2e6;
    }
</style>

templates/partial/_new-navbar.html
{% load static %}
<div class="navbar-wrapper">
<header class="navbar navbar-expand-lg ">
    <div class="container-fluid d-flex justify-content-between align-items-center">
        <!-- Logo -->
        <a href="/" class="navbar-brand">
            <img src="{% static 'frontend_assets/images/logo-1.png' %}" alt="Logo" width="160">
        </a>

        <!-- Navbar Toggle for Mobile View -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu"
            aria-controls="navbarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar Menu -->
        <div class="collapse navbar-collapse justify-content-end" id="navbarMenu">
            <button class="btn-close text-reset d-lg-none ms-auto me-2" id="closeNavbarMenu" type="button"
                aria-label="Close"></button>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/home/' %}active{% endif %}"
                        href="{% url 'userapp:new_index_page' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/trainers/' %}active{% endif %}"
                        href="{% url 'userapp:new_about_page' %}">Trainers</a>
                </li>
                {% endif %}
                <!--<li class="nav-item">
                    <a class="nav-link {% if request.path == '/courses/' %}active{% endif %}"
                        href="#">Courses Offering</a>
                </li>-->
                 <li class="nav-item">
                    <a class="nav-link {% if request.path == '/my-enrolled-courses/' %}active{% endif %}"
                        href="{% url 'userapp:feedback-List' %}">Stories</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/course-calendar/' %}active{% endif %}"
                        href="{% url 'userapp:new_courses_calendar_page' %}">Courses</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/stories/' %}active{% endif %}"
                        href="{% url 'userapp:new_stories_page' %}">Stories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/contact/' %}active{% endif %}"
                        href="{% url 'userapp:new_contact_page' %}">Contact</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/my-enrolled-courses/' %}active{% endif %}"
                        href="{% url 'userapp:applied_courses' %}">My Enrolled Courses</a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link {% if request.path == '/my-profile/' %}active{% endif %}"
                        href="{% url 'userapp:user_profile_view' %}">My Profile</a>
                </li>

                <li class="nav-item ">
                    <form method="POST" action="{% url 'userapp:logout' %}" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            Logout
                        </button>
                    </form>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="btn login-btn"
                        href="{% url 'userapp:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'userapp:new_registration_page' %}"
                        class="btn btn-primary">Register</a>
                </li>


                {% endif %}
            </ul>
        </div>
    </div>
</header>
</div>